name: Release NodeJS app

on:
  push:
    branches:
      - main

defaults:
    run:
        working-directory: ./express-app/

# Job called build runs-on ubuntu-latest
jobs:  
    publish-docker-hub:
      name: Publish image to Docker Hub
      runs-on: ubuntu-latest
      steps:
      # Checkout to the repository
      - uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      # We need to login so we can later push the image without issues.
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      # Builds devopsdockeruh/docker-hy.github.io
      - name: Build and push
        uses: docker/build-push-action@v4       
        with:
          push: true
          tags: jukkaatschool/devopswithdocker2023:latest 
      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}      
      - name: Build and deploy Container App
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }}
          registryUrl: registry.hub.docker.com
          imageToDeploy: jukkaatschool/devopswithdocker2023:latest
          registryUsername: ${{ secrets.DOCKERHUB_USERNAME }}
          registryPassword: ${{ secrets.DOCKERHUB_TOKEN }}
          containerAppName: devopsdocker2023
      # Force image pull on container app
      - name: Azure CLI script
        uses: azure/CLI@v1
        with:
          azcliversion: 2.46.0
          inlineScript: |
            az account show
            az containerapp update --name devopsdocker2023 --resource-group rg-containerapp --image jukkaatschool/devopswithdocker2023:latest                                                           